name: Run SonarCloud and Fix Vulnerability

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=arsalanraja987
            -Dsonar.projectKey=arsalanraja987_java-vuln-demo

      - name: Make fix.sh executable
        run: chmod +x ./fix.sh

      - name: Run fix.sh
        run: ./fix.sh

      - name: Commit and Push Fix
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -u
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto fix vulnerability"
            git push
          fi
