name: auto-fix

on:
  push:
    branches:
      - main

jobs:
  auto-fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Make fix.sh executable
      run: chmod +x fix.sh

    - name: Run fix.sh
      run: ./fix.sh

    - name: Commit and Push Fix
      run: |
        git config --global user.name "AutoFix Bot"
        git config --global user.email "autofix@example.com"
        git add .
        git commit -m "Auto-fixed path traversal vulnerability" || echo "No changes to commit"
        git push origin HEAD:main
